---
- name: tokens | copy tokens generation script
  copy:
    src: "kube-gen-token.sh"
    dest: "{{ kube_script_dir }}/kube-gen-token.sh"
    mode: 0700
  when: inventory_hostname == groups['kube-master'][0]

- name: tokens | generate tokens for master components
  command: "{{ kube_script_dir }}/kube-gen-token.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_nested:
    - [ "system:kubectl" ]
    - "{{ groups['kube-master'] }}"
  register: gentoken_master
  changed_when: "'Added' in gentoken_master.stdout"
  notify: set secret_changed
  when: inventory_hostname == groups['kube-master'][0]

- name: tokens | generate tokens for node components
  command: "{{ kube_script_dir }}/kube-gen-token.sh {{ item[0] }}-{{ item[1] }}"
  environment:
    TOKEN_DIR: "{{ kube_token_dir }}"
  with_nested:
    - [ 'system:kubelet' ]
    - "{{ groups['kube-node'] }}"
  register: gentoken_node
  changed_when: "'Added' in gentoken_node.stdout"
  notify: set secret_changed
  when: inventory_hostname == groups['kube-master'][0]

- name: tokens | Get list of tokens from first master
  shell: "(find {{ kube_token_dir }} -maxdepth 1 -type f)"
  register: tokens_list
  changed_when: false
  when: inventory_hostname == groups['kube-master'][0]

- name: tokens | Download tokens from first master
  fetch:
    src: "{{ item }}"
    dest: "{{ role_path }}/files/tokens/"
    flat: yes
  with_items: '{{tokens_list.stdout_lines}}'
  when: inventory_hostname == groups['kube-master'][0]

- name: tokens | Copy tokens on master
  copy:
    src: "tokens"
    dest: "/etc/kubernetes"
  when: inventory_hostname in "{{ groups['kube-master'] }}" and
        inventory_hostname != "{{ groups['kube-master'][0] }}"
